### ISSUE TITLE
GOOS and GOARCH for Mac with Apple Sillicon

### ISSUE THREAD

**Issue by lsotodev** [rogerscuall/aws-router#1]
# GOOS and GOARCH for Mac with Apple Sillicon

## [Context](https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63):

> With the introduction of Apple Silicon (a.k.a. the M1 chip), on go version 1.16 or later:
>   * darwin/amd64 means macOS with Intel CPU
>   * darwin/arm64 updates to mean macOS with Apple Silicon CPU

## Task:

* Replace the following code segment: 

https://github.com/rogerscuall/aws-router/blob/05633e7991e2bb58a4566985afa8f75d31975de4/Taskfile.yaml#L13-L21

with:

```
 build: 
   cmds: 
     - GOOS=darwin GOARCH=arm64 go build -o awsrouters-m1 *.go 
  buildMacIntel: 
   cmds: 
     - GOOS=darwin GOARCH=amd64 go build -o awsrouters-intel *.go
 buildWindows: 
   cmds: 
     - GOOS=windows GOARCH=amd64 go build -o awsrouters.exe *.go 
 buildLinux: 
   cmds: 
     - GOOS=linux GOARCH=amd64 go build -o awsrouters-linux
```

### Allow build for the follow 4 OS/Arch convention: 

* MacOS ARM64 (Apple Sillicon)
* MacOS AMD64
* Windows AMD64
* Linux AMD64

cc: @rogerscuall, @lsotodev
